"""empty message

Revision ID: 286163916881
Revises: 190163627111
Create Date: 2015-09-23 20:29:14.506375

"""

# revision identifiers, used by Alembic.
revision = '286163916881'
down_revision = '190163627111'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
